# This is the name of your worker
name = "resulta" 
main = "src/index.js" # This points to your main code file
compatibility_date = "2024-05-01"

# --- THIS IS THE FIX ---
# This tells the worker to run the cron job EVERY 5 MINUTES
[triggers]
crons = ["*/5 * * * *"] 

# This connects your code to the KV database (which is FREE)
[[kv_namespaces]]
binding = "RETRY_QUEUE"
id = "8e81ee4408ca457f8b3ce6e6ae10330c"
