# This is the name of your worker
name = "resulta" 
main = "src/index.js" # This points to your main code file
compatibility_date = "2024-05-01"

# This tells the worker to run the cron job every hour
[triggers]
crons = ["0 * * * *"] # (Runs at minute 0 of every hour)

# This connects your code to the KV database
# We will get the ID in the next step
[[kv_namespaces]]
binding = "RETRY_QUEUE"
id = "PASTE_YOUR_ID_HERE"
