# This is the name of your worker
name = "resulta" 
main = "src/index.js" # This points to your main code file
compatibility_date = "2024-05-01"

# This section tells your main 'fetch' worker that it can 
# send messages TO the queue
[[queues.producers]]
queue = "RETRY_QUEUE"
binding = "RETRY_QUEUE" # This makes it available in the code as env.RETRY_QUEUE

# This section tells the queue to trigger this SAME worker 
# when it receives a message
[[queues.consumers]]
queue = "RETRY_QUEUE"
